# Generated by Django 5.2.17 on 2026-09-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, help_text='Street, suburb, postcode. Only you can see it.', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text="However you'd write it. Only you can see it.", max_length=32),
        ),
    ]
