# Generated by Django 5.2.17 on 2026-09-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0003_replies_and_comment_reactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='emoji',
            field=models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('🥰', 'Care'), ('😂', 'Haha'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry')], max_length=8),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='emoji',
            field=models.CharField(choices=[('👍', 'Like'), ('❤️', 'Love'), ('🥰', 'Care'), ('😂', 'Haha'), ('😮', 'Wow'), ('😢', 'Sad'), ('😡', 'Angry')], max_length=8),
        ),
    ]
