# Generated by Django 5.2.17 on 2026-09-17 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0004_care_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Only me')], default='public', max_length=8),
        ),
        migrations.AddField(
            model_name='notice',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Only me')], default='public', max_length=8),
        ),
    ]
