# Generated by Django 5.2.17 on 2026-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0005_comment_visibility_notice_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
