# Generated by Django 5.2.17 on 2026-09-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0006_comment_hidden_notice_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='pinned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
