# Generated by Django 5.2.17 on 2026-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0006_fortnights_start_on_thursday'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(212, 'Blue'), (150, 'Green'), (32, 'Orange'), (272, 'Violet'), (330, 'Pink'), (188, 'Teal'), (56, 'Amber'), (108, 'Lime')], default=212, verbose_name='Colour'),
        ),
    ]
