# Generated by Django 5.2.17 on 2026-09-08 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0008_spread_workplace_colours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covers_through', models.DateTimeField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='timeclock.workplace')),
            ],
            options={
                'ordering': ['-covers_through'],
                'indexes': [models.Index(fields=['workplace', '-covers_through'], name='timeclock_p_workpla_bd9a51_idx')],
            },
        ),
    ]
