# Generated by Django 5.2.17 on 2026-09-13 23:13

import apps.stories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='kind',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=5),
        ),
        migrations.AddField(
            model_name='story',
            name='video',
            field=models.FileField(blank=True, upload_to=apps.stories.models.story_path),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.stories.models.story_path),
        ),
    ]
