# Generated by Django 5.2.17 on 2026-09-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
