# Generated by Django 5.2.17 on 2026-09-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_story_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only'), ('private', 'Only me')], default='public', max_length=8),
        ),
    ]
