# Generated by Django 5.2.17 on 2026-09-18 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='one_block_per_pair')],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('notice', 'Notice'), ('comment', 'Comment'), ('story', 'Story'), ('user', 'Person')], max_length=8)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('spam', 'Spam or misleading'), ('harassment', 'Harassment or bullying'), ('hate', 'Hate speech or violence'), ('sexual', 'Nudity or sexual content'), ('other', 'Something else')], default='other', max_length=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('excerpt', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('accused', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'target_id'], name='moderation__kind_5980a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'kind', 'target_id'), name='one_report_per_person_per_thing')],
            },
        ),
    ]
