# Generated by Django 5.2.12 on 2026-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plu_no', models.PositiveIntegerField(db_index=True, unique=True)),
                ('description', models.CharField(db_index=True, max_length=255)),
                ('sales_mode', models.CharField(default='Weight', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tare', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plu_no'],
            },
        ),
    ]
