# Generated by Django 5.2.12 on 2026-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='pluitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pluitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pluitem',
            name='sales_mode',
        ),
        migrations.RemoveField(
            model_name='pluitem',
            name='tare',
        ),
        migrations.RemoveField(
            model_name='pluitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pluitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pluitem',
            name='plu_no',
            field=models.IntegerField(unique=True),
        ),
    ]
