# Generated by Django 5.2.17 on 2026-09-07 00:45

import django.db.models.deletion
import apps.timeclock.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('ON_BREAK', 'On break'), ('COMPLETED', 'Completed')], default='WORKING', max_length=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in'],
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start', models.DateTimeField()),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='timeclock.shift')),
            ],
            options={
                'ordering': ['break_start'],
            },
        ),
        migrations.CreateModel(
            name='TimePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('limit_period', models.CharField(choices=[('WEEK', 'Per week'), ('FORTNIGHT', 'Per fortnight')], default='FORTNIGHT', max_length=9)),
                ('fortnight_anchor', models.DateField(default=apps.timeclock.models._monday_of_this_week)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_pref', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Used to estimate pay alongside your hours.', max_digits=7, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='workplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='timeclock.workplace'),
        ),
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('user', 'name'), name='uniq_active_workplace_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['user', '-clock_in'], name='timeclock_s_user_id_98e7b1_idx'),
        ),
    ]
