# Generated by Django 5.2.17 on 2026-09-07 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0004_cycle_starts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional. Take it off a payslip: tax withheld ÷ gross × 100.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
