# Generated by Django 5.2.17 on 2026-09-07 13:31

import apps.timeclock.models
from datetime import timedelta

from django.db import migrations, models

# Weekday numbering is date.weekday()'s: Monday 0 ... Thursday 3.
THURSDAY = 3


def snap_anchors_to_thursday(apps, schema_editor):
    """
    Move every existing fortnight anchor back to the Thursday of its own week.

    A cycle repeats every 14 days, so the anchor's weekday is the weekday the
    cycle starts on for good. Anchors already on a Thursday are left exactly
    where they are — moving them would flip which of the two alternating
    fortnights a shift belongs to, and those are already lined up with real
    pay periods. Everything else moves backwards to the Thursday before it,
    so an anchor stays in the past where an anchor belongs.
    """
    for name in ("Workplace", "TimePreference"):
        model = apps.get_model("timeclock", name)
        for row in model.objects.filter(fortnight_anchor__isnull=False).iterator():
            drift = (row.fortnight_anchor.weekday() - THURSDAY) % 7
            if drift:
                row.fortnight_anchor -= timedelta(days=drift)
                row.save(update_fields=["fortnight_anchor"])


def leave_anchors_alone(apps, schema_editor):
    """
    Nothing to undo: the dates they held before are not recorded anywhere,
    and every anchor here is still a valid cycle start.
    """


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0005_workplace_tax_rate'),
    ]

    operations = [
        migrations.RunPython(snap_anchors_to_thursday, leave_anchors_alone),
        migrations.AlterField(
            model_name='timepreference',
            name='fortnight_anchor',
            field=models.DateField(default=apps.timeclock.models._recent_fortnight_start),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='fortnight_anchor',
            field=models.DateField(default=apps.timeclock.models._recent_fortnight_start),
        ),
    ]
