# Generated by Django 5.2.17 on 2026-09-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0009_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='pay_cycle',
            field=models.CharField(choices=[('IRREGULAR', "Whenever I'm paid"), ('WEEK', 'Weekly'), ('FORTNIGHT', 'Fortnightly'), ('MONTH', 'Monthly')], default='IRREGULAR', max_length=9),
        ),
    ]
