# Generated by Django 5.2.17 on 2026-09-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0010_workplace_pay_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='covers_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
