# Generated by Django 5.2.17 on 2026-09-08 20:44

import django.db.models.deletion
from django.db import migrations, models


def payslip_path(instance, filename):
    """Where an uploaded payslip landed.

    A copy of what used to live in models.py. The model this migration
    creates is dropped again a few migrations later, and the function went
    with it — but a migration has to keep running from an empty database
    long after the code it was written against has gone, and upload_to is
    resolved when the file is read. It is never called: nothing saves a
    payslip any more.
    """
    suffix = (filename.rsplit(".", 1)[-1] or "dat").lower()
    return f"payslips/{instance.workplace.user_id}/{filename}.{suffix}"


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0011_payment_covers_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to=payslip_path)),
                ('source', models.CharField(choices=[('PDF', 'PDF'), ('PHOTO', 'Photo'), ('TYPED', 'Typed in')], default='TYPED', max_length=5)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('super_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Superannuation')),
                ('confirmed', models.BooleanField(default=False)),
                ('raw_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='timeclock.workplace')),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['workplace', '-period_end'], name='timeclock_p_workpla_494949_idx')],
            },
        ),
    ]
