# Generated by Django 5.2.17 on 2026-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0012_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='paid_in',
            field=models.CharField(choices=[('BANK', 'Into my account, with tax taken out'), ('CASH', 'Cash in hand')], default='BANK', max_length=4, verbose_name="How you're paid"),
        ),
    ]
