# Generated by Django 5.2.17 on 2026-09-09 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0013_workplace_paid_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workplace',
            name='uniq_active_workplace_name_per_user',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='is_archived',
        ),
        migrations.AddConstraint(
            model_name='workplace',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_active_workplace_name_per_user'),
        ),
    ]
