# Generated by Django 5.2.17 on 2026-09-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0014_remove_workplace_uniq_active_workplace_name_per_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
