# Generated by Django 5.2.17 on 2026-09-30 09:19

from django.db import migrations, models


def percentages_stay_percentages(apps, schema_editor):
    """A job that already had a percentage keeps working out tax by it."""
    Workplace = apps.get_model("timeclock", "Workplace")
    Workplace.objects.filter(tax_rate__isnull=False).update(tax_scale="CUSTOM")


class Migration(migrations.Migration):

    dependencies = [
        ('timeclock', '0015_delete_payslip'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplace',
            name='study_loan',
            field=models.BooleanField(default=False, verbose_name='I have a HELP or other study loan'),
        ),
        migrations.AddField(
            model_name='workplace',
            name='tax_scale',
            field=models.CharField(blank=True, choices=[('TFT', 'Tax-free threshold claimed'), ('NO_TFT', 'No tax-free threshold (2nd job)'), ('FOREIGN', 'Foreign resident'), ('WHM', 'Working holiday maker (417/462)'), ('NO_TFN', 'No TFN given'), ('CUSTOM', 'My own % from a payslip')], default='', max_length=8, verbose_name='Your tax situation here'),
        ),
        migrations.RunPython(percentages_stay_percentages, migrations.RunPython.noop),
    ]
