# Generated by Django 5.2.17 on 2026-10-08 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plu', '0002_alter_pluitem_options_remove_pluitem_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('headers', models.JSONField()),
                ('rows', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pluitem',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pluitem',
            name='fields',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='pluitem',
            name='search_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pluitem',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pluitem',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pluitem',
            name='plu_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My items', max_length=100)),
                ('headers', models.JSONField(default=list)),
                ('title_column', models.CharField(max_length=100)),
                ('description_column', models.CharField(blank=True, max_length=100)),
                ('code_column', models.CharField(blank=True, max_length=100)),
                ('search_columns', models.JSONField(default=list)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_catalogue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pluitem',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plu.catalogue'),
        ),
        migrations.AddConstraint(
            model_name='pluitem',
            constraint=models.UniqueConstraint(fields=('catalogue', 'plu_no'), name='private_plu_number'),
        ),
        migrations.AddField(
            model_name='catalogueupload',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
