# Generated by Django 5.2.17 on 2026-10-09 00:29

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plu', '0003_catalogueupload_pluitem_code_pluitem_fields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueupload',
            name='filename',
            field=models.CharField(default='items.csv', max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_catalogues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='catalogue',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('owner'), name='private_catalogue_name'),
        ),
    ]
