# Generated by Django 5.2.17 on 2026-09-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('notice', 'New notice'), ('comment', 'Comment'), ('reply', 'Reply'), ('reaction', 'Reaction'), ('timesheet', 'Timesheet'), ('friend_request', 'Friend request'), ('friend_accepted', 'Friend accepted')], max_length=16),
        ),
    ]
