# Generated by Django 5.2.17 on 2026-09-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_kind_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pushed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
